export const data=[
    {
        "Title": "The Dark Knight",
        "year": "2008",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            4,
            1,
            6,
            10,
            6,
            3,
            5,
            9,
            1,
            3,
            1,
            7,
            8,
            10,
            6,
            2,
            8,
            6,
            7,
            1,
            4,
            3,
            8,
            3,
            10,
            8,
            10,
            4
        ],
        "poster": "MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT152M",
        "releaseDate": "2008-07-25",
        "averageRating": 0,
        "originalTitle": "",
        "Plot": "Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman's struggle against the Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.                Written by\nLeon Lombardi",
        "actors": [
            "Christian Bale",
            "Heath Ledger",
            "Aaron Eckhart"
        ],
        "imdbRating": 9.0,
        "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "Title": "12 edsvurna m\u00e4n",
        "year": "1957",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            5,
            3,
            3,
            10,
            3,
            4,
            1,
            6,
            10,
            2,
            8,
            4,
            6,
            8,
            6,
            1,
            10,
            4,
            5,
            9,
            3,
            2,
            4,
            8,
            10,
            10,
            7,
            9,
            6
        ],
        "poster": "MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT96M",
        "releaseDate": "1957-07-29",
        "averageRating": 0,
        "originalTitle": "12 Angry Men",
        "Plot": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.                Written by\npjk <PETESID@VNET.IBM.COM>",
        "actors": [
            "Henry Fonda",
            "Lee J. Cobb",
            "Martin Balsam"
        ],
        "imdbRating": 8.9,
        "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
        "Title": "Schindler's List",
        "year": "1993",
        "genres": [
            "Biography",
            "Drama",
            "History"
        ],
        "ratings": [
            2,
            6,
            7,
            8,
            8,
            6,
            2,
            4,
            6,
            2,
            3,
            3,
            5,
            9,
            5,
            10,
            9,
            5,
            5,
            2,
            10,
            4,
            8,
            7,
            4,
            10,
            2,
            10,
            4,
            10
        ],
        "poster": "MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT195M",
        "releaseDate": "1994-03-04",
        "averageRating": 0,
        "originalTitle": "",
        "Plot": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.                Written by\nHarald Mayr <marvin@bike.augusta.de>",
        "actors": [
            "Liam Neeson",
            "Ralph Fiennes",
            "Ben Kingsley"
        ],
        "imdbRating": 8.9,
        "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg"
    }
]